CREATE TABLE projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    features TEXT,
    author TEXT,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
)